from handlers.users.start import db
from utils.db_api.db_commands import add_new_profile
import asyncio

from utils.db_api.database import create_db


# Используем эту функцию, чтобы заполнить базу данных
async def add_new_profiles():
    await add_new_profile(
        user_id=5555555555,
        name='Petr',
        username='petr_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=18,
        gender='Парень',
        purpose='Просто поиграть',
        who_search='Девушек',
        country='Россия',
        city='Москва',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555556,
        name='Катя',
        username='kat_2021',
        language='🇷🇺 Русский',
        game1='',
        game2='PUBG New State',
        age=25,
        gender='Девушка',
        purpose='Человека в реальной жизни',
        who_search='Парней',
        country='Россия',
        city='Саратов',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555557,
        name='Света',
        username='sv_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='',
        age=17,
        gender='Девушка',
        purpose='Команду для праков',
        who_search='Девушек',
        country='Россия',
        city='Москва',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555558,
        name='Kristina',
        username='kris_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=33,
        gender='Девушка',
        purpose='Просто поиграть',
        who_search='Парней',
        country='USA',
        city='Chicago',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555559,
        name='John',
        username='john_2021',
        language='🇷🇺 Русский',
        game1='',
        game2='PUBG New State',
        age=28,
        gender='Парень',
        purpose='Команду для праков',
        who_search='Парней',
        country='USA',
        city='LA',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555554,
        name='Юра',
        username='ur_2021',
        language='🇷🇺 Русский',
        game1='',
        game2='PUBG New State',
        age=35,
        gender='Парень',
        purpose='Команду для праков',
        who_search='Парней',
        country='Россия',
        city='Москва',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555553,
        name='Витя',
        username='viktor_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=40,
        gender='Парень',
        purpose='Просто поиграть',
        who_search='Девушек',
        country='Россия',
        city='Москва',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555552,
        name='Макс',
        username='max_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='',
        age=30,
        gender='Парень',
        purpose='Человека в реальной жизни',
        who_search='Девушек',
        country='Россия',
        city='Москва',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555551,
        name='Вова',
        username='vov_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=23,
        gender='Парень',
        purpose='Человека в реальной жизни',
        who_search='Девушек',
        country='Россия',
        city='Волгоград',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555511,
        name='Надя',
        username='nnn_2021',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=27,
        gender='Девушка',
        purpose='Человека в реальной жизни',
        who_search='Парней',
        country='Россия',
        city='Волгоград',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=5555555522,
        name='Vanessa',
        username='va_2021',
        language='🇷🇺 Русский',
        game1='',
        game2='',
        age=16,
        gender='Girl',
        purpose='Просто поиграть',
        who_search='Guys',
        country='USA',
        city='LA',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=254824178,
        name='Диана',
        username='di_2021',
        language='🇷🇺 Русский',
        game1='',
        game2='',
        age=37,
        gender='Девушка',
        purpose='Команду для праков',
        who_search='Парней',
        hobby='',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=1027394288,
        name='Костя',
        username='kos_2021',
        language='🇷🇺 Русский',
        game1='PUBG New State',
        game2='',
        age=35,
        gender='Парень',
        purpose='Команду для праков',
        who_search='Девушек',
        country='Россия',
        city='Москва',
        hobby='Нет',
        photo='http://telegra.ph//file/4b380dae2a25deba66ce0.jpg'
    ),
    await add_new_profile(
        user_id=1815257967,
        name='Андрей',
        username='boost_ace',
        language='🇷🇺 Русский',
        game1='PUBG MOBILE',
        game2='PUBG New State',
        age=35,
        gender='Парень',
        purpose='Просто поиграть',
        who_search='Парней и Девушек',
        country='Россия',
        city='Нижний Новгород',
        hobby='Нет',
        photo='http://telegra.ph//file/4f70e4c1d06c2de7fbe6d.jpg'
    )


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(create_db())
    # loop.run_until_complete(add_new_profiles())
